### ISSUE TITLE
`fractive help` doesn't work on headless Ubuntu

### ISSUE THREAD

**Issue by audiodude** [invicticide/fractive#88]
# What happened

```
$ fractive help
Couldn't get a file descriptor referring to the console
Error: Command failed: open /home/<REDACTED>/code/fractive/doc/build/index.html
Couldn't get a file descriptor referring to the console

    at checkExecSyncError (child_process.js:575:11)
    at Object.execSync (child_process.js:612:13)
    at HandleArgs (/home/<REDACTED>/code/fractive/src/CLI.ts:146:15)
    at Object.<anonymous> (/home/<REDACTED>/code/fractive/src/CLI.ts:193:2)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
```

# Steps to reproduce
Type fractive help after installing a dev version of fractive (`npm install -g .`)

# Expected behavior
Shows a help page.

**Comment by NQNStudios** [comment]
I get the same result on Ubuntu GamePack 16.04 while running a window manager. I'll look into fixing this.

**Comment by invicticide** [comment]
If I understand this issue and PR #93 correctly, I think this should be resolved now...? (I think?)

**Comment by audiodude** [comment]
Yes this is fixed.
